@startuml

title [クラス図]

' === 定義 ===
package android {
    class SharedPreferences
    class Notification
}

class MainActivity <<Activity>> {
    + showCounter()
    + showResetCountScreen()
}

class MeasurementReceiver <<BroadcastReceiver>> {
    + onREceive()
}

class MeasurementService <<Service>> {

}

package user.present.count {
    class UserPresentReceiver <<BroadcastReceiver>> {
        + onReceive()
    }

    class RecordService <<Service>> {
        + onStartCommand()
    }

    class DisplayCountFragment <<Fragment>> {
        + showCounter()
    }

    class DisplayCountViewModel <<ViewModel>> {
    }

    class ResetTotalCountFragment <<Fragment>> {
        + resetTotalCount()
        - saveTotalCount()
    }

    class ResetTotalCountViewModel <<ViewModel>> {

    }
}

package data {
    class UserPresentCountRepository
    class UserPresentCountLocalDataSource
    class UserPresentCount
}

' === 関係 ===
MainActivity "1" o-- "1" MeasurementReceiver
MeasurementReceiver --> MeasurementService : start / stop >
MeasurementService "1" o-- "1" UserPresentReceiver
MeasurementService "1" -- "1" Notification : create >
UserPresentReceiver "1" -- "1" RecordService : use >
RecordService "1" o--> "1" UserPresentCountRepository
UserPresentCountRepository "1" o--> "1" UserPresentCountLocalDataSource
UserPresentCountLocalDataSource "1" ..> "1" UserPresentCount
UserPresentCountLocalDataSource "1" --> "1" SharedPreferences

MainActivity -- DisplayCountFragment : create >
MainActivity -- ResetTotalCountFragment : create >
DisplayCountFragment -- DisplayCountViewModel
ResetTotalCountFragment -- ResetTotalCountViewModel
DisplayCountViewModel -- UserPresentCountRepository
ResetTotalCountViewModel -- UserPresentCountRepository

@enduml