@startuml

' == メリット ==
' 1. 顧客の要求を明確化できる
' 2. システムの範囲（できること・できないこと）を明確化できる

' == ポイント ==
' システム利用者（アクター）視点で書く
' シンプルに書く
' 機能分割しない（機能仕様ではない）
' ユースケースの粒度を統一する
' 表現を統一する

left to right direction
skinparam shadowing false

' ======================================================
actor スマホ所有者

usecase 今日キーガードを解除した回数を確認する as UC1
usecase 過去のキーガードを解除した回数を確認する as UC2
usecase 今日のキーガードを解除した回数をリセットする as UC3
usecase カウントの停止 as UC4
usecase カウントの再開 as UC5
' ======================================================
スマホ所有者 -- UC1
スマホ所有者 -- UC2
スマホ所有者 -- UC3
スマホ所有者 -- UC4
スマホ所有者 -- UC5

@enduml